<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>AnimalApparelCollarsAndKit.Settings</AssemblyName>
    <OutputPath>../Mod/Mods/VEF/Assemblies/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>none</DebugType>
    <Deterministic>true</Deterministic>
    <RimWorldManaged Condition="'$(RimWorldManaged)' == ''">C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin64_Data/Managed</RimWorldManaged>
    <VefAssembly Condition="'$(VefAssembly)' == ''">C:/Program Files (x86)/Steam/steamapps/workshop/content/294100/2023507013/1.6/Assemblies/VEF.dll</VefAssembly>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>$(RimWorldManaged)/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(RimWorldManaged)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(RimWorldManaged)/UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="VEF"><HintPath>$(VefAssembly)</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
